package life.mashangkaishi.manongcommunity.model;

public class Administrator {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column administrator.id
     *
     * @mbg.generated Mon Dec 23 02:03:46 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column administrator.username
     *
     * @mbg.generated Mon Dec 23 02:03:46 CST 2019
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column administrator.password
     *
     * @mbg.generated Mon Dec 23 02:03:46 CST 2019
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column administrator.sex
     *
     * @mbg.generated Mon Dec 23 02:03:46 CST 2019
     */
    private Integer sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column administrator.departments
     *
     * @mbg.generated Mon Dec 23 02:03:46 CST 2019
     */
    private String departments;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column administrator.state
     *
     * @mbg.generated Mon Dec 23 02:03:46 CST 2019
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column administrator.email
     *
     * @mbg.generated Mon Dec 23 02:03:46 CST 2019
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column administrator.security_issue
     *
     * @mbg.generated Mon Dec 23 02:03:46 CST 2019
     */
    private String securityIssue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column administrator.verification
     *
     * @mbg.generated Mon Dec 23 02:03:46 CST 2019
     */
    private Integer verification;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column administrator.gmt_create
     *
     * @mbg.generated Mon Dec 23 02:03:46 CST 2019
     */
    private Integer gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column administrator.my_student
     *
     * @mbg.generated Mon Dec 23 02:03:46 CST 2019
     */
    private String myStudent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column administrator.id
     *
     * @return the value of administrator.id
     *
     * @mbg.generated Mon Dec 23 02:03:46 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column administrator.id
     *
     * @param id the value for administrator.id
     *
     * @mbg.generated Mon Dec 23 02:03:46 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column administrator.username
     *
     * @return the value of administrator.username
     *
     * @mbg.generated Mon Dec 23 02:03:46 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column administrator.username
     *
     * @param username the value for administrator.username
     *
     * @mbg.generated Mon Dec 23 02:03:46 CST 2019
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column administrator.password
     *
     * @return the value of administrator.password
     *
     * @mbg.generated Mon Dec 23 02:03:46 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column administrator.password
     *
     * @param password the value for administrator.password
     *
     * @mbg.generated Mon Dec 23 02:03:46 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column administrator.sex
     *
     * @return the value of administrator.sex
     *
     * @mbg.generated Mon Dec 23 02:03:46 CST 2019
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column administrator.sex
     *
     * @param sex the value for administrator.sex
     *
     * @mbg.generated Mon Dec 23 02:03:46 CST 2019
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column administrator.departments
     *
     * @return the value of administrator.departments
     *
     * @mbg.generated Mon Dec 23 02:03:46 CST 2019
     */
    public String getDepartments() {
        return departments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column administrator.departments
     *
     * @param departments the value for administrator.departments
     *
     * @mbg.generated Mon Dec 23 02:03:46 CST 2019
     */
    public void setDepartments(String departments) {
        this.departments = departments == null ? null : departments.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column administrator.state
     *
     * @return the value of administrator.state
     *
     * @mbg.generated Mon Dec 23 02:03:46 CST 2019
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column administrator.state
     *
     * @param state the value for administrator.state
     *
     * @mbg.generated Mon Dec 23 02:03:46 CST 2019
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column administrator.email
     *
     * @return the value of administrator.email
     *
     * @mbg.generated Mon Dec 23 02:03:46 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column administrator.email
     *
     * @param email the value for administrator.email
     *
     * @mbg.generated Mon Dec 23 02:03:46 CST 2019
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column administrator.security_issue
     *
     * @return the value of administrator.security_issue
     *
     * @mbg.generated Mon Dec 23 02:03:46 CST 2019
     */
    public String getSecurityIssue() {
        return securityIssue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column administrator.security_issue
     *
     * @param securityIssue the value for administrator.security_issue
     *
     * @mbg.generated Mon Dec 23 02:03:46 CST 2019
     */
    public void setSecurityIssue(String securityIssue) {
        this.securityIssue = securityIssue == null ? null : securityIssue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column administrator.verification
     *
     * @return the value of administrator.verification
     *
     * @mbg.generated Mon Dec 23 02:03:46 CST 2019
     */
    public Integer getVerification() {
        return verification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column administrator.verification
     *
     * @param verification the value for administrator.verification
     *
     * @mbg.generated Mon Dec 23 02:03:46 CST 2019
     */
    public void setVerification(Integer verification) {
        this.verification = verification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column administrator.gmt_create
     *
     * @return the value of administrator.gmt_create
     *
     * @mbg.generated Mon Dec 23 02:03:46 CST 2019
     */
    public Integer getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column administrator.gmt_create
     *
     * @param gmtCreate the value for administrator.gmt_create
     *
     * @mbg.generated Mon Dec 23 02:03:46 CST 2019
     */
    public void setGmtCreate(Integer gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column administrator.my_student
     *
     * @return the value of administrator.my_student
     *
     * @mbg.generated Mon Dec 23 02:03:46 CST 2019
     */
    public String getMyStudent() {
        return myStudent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column administrator.my_student
     *
     * @param myStudent the value for administrator.my_student
     *
     * @mbg.generated Mon Dec 23 02:03:46 CST 2019
     */
    public void setMyStudent(String myStudent) {
        this.myStudent = myStudent == null ? null : myStudent.trim();
    }
}