package life.mashangkaishi.manongcommunity.model;

public class Class {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.id
     *
     * @mbg.generated Thu Jan 23 10:41:11 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.class_number
     *
     * @mbg.generated Thu Jan 23 10:41:11 CST 2020
     */
    private Integer classNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.class_name
     *
     * @mbg.generated Thu Jan 23 10:41:11 CST 2020
     */
    private String className;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.students
     *
     * @mbg.generated Thu Jan 23 10:41:11 CST 2020
     */
    private String students;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.main_teacher
     *
     * @mbg.generated Thu Jan 23 10:41:11 CST 2020
     */
    private String mainTeacher;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.teachers
     *
     * @mbg.generated Thu Jan 23 10:41:11 CST 2020
     */
    private String teachers;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.id
     *
     * @return the value of class.id
     *
     * @mbg.generated Thu Jan 23 10:41:11 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.id
     *
     * @param id the value for class.id
     *
     * @mbg.generated Thu Jan 23 10:41:11 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.class_number
     *
     * @return the value of class.class_number
     *
     * @mbg.generated Thu Jan 23 10:41:11 CST 2020
     */
    public Integer getClassNumber() {
        return classNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.class_number
     *
     * @param classNumber the value for class.class_number
     *
     * @mbg.generated Thu Jan 23 10:41:11 CST 2020
     */
    public void setClassNumber(Integer classNumber) {
        this.classNumber = classNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.class_name
     *
     * @return the value of class.class_name
     *
     * @mbg.generated Thu Jan 23 10:41:11 CST 2020
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.class_name
     *
     * @param className the value for class.class_name
     *
     * @mbg.generated Thu Jan 23 10:41:11 CST 2020
     */
    public void setClassName(String className) {
        this.className = className == null ? null : className.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.students
     *
     * @return the value of class.students
     *
     * @mbg.generated Thu Jan 23 10:41:11 CST 2020
     */
    public String getStudents() {
        return students;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.students
     *
     * @param students the value for class.students
     *
     * @mbg.generated Thu Jan 23 10:41:11 CST 2020
     */
    public void setStudents(String students) {
        this.students = students == null ? null : students.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.main_teacher
     *
     * @return the value of class.main_teacher
     *
     * @mbg.generated Thu Jan 23 10:41:11 CST 2020
     */
    public String getMainTeacher() {
        return mainTeacher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.main_teacher
     *
     * @param mainTeacher the value for class.main_teacher
     *
     * @mbg.generated Thu Jan 23 10:41:11 CST 2020
     */
    public void setMainTeacher(String mainTeacher) {
        this.mainTeacher = mainTeacher == null ? null : mainTeacher.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.teachers
     *
     * @return the value of class.teachers
     *
     * @mbg.generated Thu Jan 23 10:41:11 CST 2020
     */
    public String getTeachers() {
        return teachers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.teachers
     *
     * @param teachers the value for class.teachers
     *
     * @mbg.generated Thu Jan 23 10:41:11 CST 2020
     */
    public void setTeachers(String teachers) {
        this.teachers = teachers == null ? null : teachers.trim();
    }
}