package life.mashangkaishi.manongcommunity.model;

public class Data {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data.data_id
     *
     * @mbg.generated Sun Feb 02 22:41:54 CST 2020
     */
    private Long dataId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data.creator
     *
     * @mbg.generated Sun Feb 02 22:41:54 CST 2020
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data.title
     *
     * @mbg.generated Sun Feb 02 22:41:54 CST 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data.gmt_create
     *
     * @mbg.generated Sun Feb 02 22:41:54 CST 2020
     */
    private String gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data.comment_count
     *
     * @mbg.generated Sun Feb 02 22:41:54 CST 2020
     */
    private Integer commentCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data.view_count
     *
     * @mbg.generated Sun Feb 02 22:41:54 CST 2020
     */
    private Integer viewCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data.like_count
     *
     * @mbg.generated Sun Feb 02 22:41:54 CST 2020
     */
    private Integer likeCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data.tag
     *
     * @mbg.generated Sun Feb 02 22:41:54 CST 2020
     */
    private String tag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data.description
     *
     * @mbg.generated Sun Feb 02 22:41:54 CST 2020
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data.data_id
     *
     * @return the value of data.data_id
     *
     * @mbg.generated Sun Feb 02 22:41:54 CST 2020
     */
    public Long getDataId() {
        return dataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data.data_id
     *
     * @param dataId the value for data.data_id
     *
     * @mbg.generated Sun Feb 02 22:41:54 CST 2020
     */
    public void setDataId(Long dataId) {
        this.dataId = dataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data.creator
     *
     * @return the value of data.creator
     *
     * @mbg.generated Sun Feb 02 22:41:54 CST 2020
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data.creator
     *
     * @param creator the value for data.creator
     *
     * @mbg.generated Sun Feb 02 22:41:54 CST 2020
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data.title
     *
     * @return the value of data.title
     *
     * @mbg.generated Sun Feb 02 22:41:54 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data.title
     *
     * @param title the value for data.title
     *
     * @mbg.generated Sun Feb 02 22:41:54 CST 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data.gmt_create
     *
     * @return the value of data.gmt_create
     *
     * @mbg.generated Sun Feb 02 22:41:54 CST 2020
     */
    public String getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data.gmt_create
     *
     * @param gmtCreate the value for data.gmt_create
     *
     * @mbg.generated Sun Feb 02 22:41:54 CST 2020
     */
    public void setGmtCreate(String gmtCreate) {
        this.gmtCreate = gmtCreate == null ? null : gmtCreate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data.comment_count
     *
     * @return the value of data.comment_count
     *
     * @mbg.generated Sun Feb 02 22:41:54 CST 2020
     */
    public Integer getCommentCount() {
        return commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data.comment_count
     *
     * @param commentCount the value for data.comment_count
     *
     * @mbg.generated Sun Feb 02 22:41:54 CST 2020
     */
    public void setCommentCount(Integer commentCount) {
        this.commentCount = commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data.view_count
     *
     * @return the value of data.view_count
     *
     * @mbg.generated Sun Feb 02 22:41:54 CST 2020
     */
    public Integer getViewCount() {
        return viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data.view_count
     *
     * @param viewCount the value for data.view_count
     *
     * @mbg.generated Sun Feb 02 22:41:54 CST 2020
     */
    public void setViewCount(Integer viewCount) {
        this.viewCount = viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data.like_count
     *
     * @return the value of data.like_count
     *
     * @mbg.generated Sun Feb 02 22:41:54 CST 2020
     */
    public Integer getLikeCount() {
        return likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data.like_count
     *
     * @param likeCount the value for data.like_count
     *
     * @mbg.generated Sun Feb 02 22:41:54 CST 2020
     */
    public void setLikeCount(Integer likeCount) {
        this.likeCount = likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data.tag
     *
     * @return the value of data.tag
     *
     * @mbg.generated Sun Feb 02 22:41:54 CST 2020
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data.tag
     *
     * @param tag the value for data.tag
     *
     * @mbg.generated Sun Feb 02 22:41:54 CST 2020
     */
    public void setTag(String tag) {
        this.tag = tag == null ? null : tag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data.description
     *
     * @return the value of data.description
     *
     * @mbg.generated Sun Feb 02 22:41:54 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data.description
     *
     * @param description the value for data.description
     *
     * @mbg.generated Sun Feb 02 22:41:54 CST 2020
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}