package life.mashangkaishi.manongcommunity.model;

public class Jobs {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jobs.id
     *
     * @mbg.generated Wed Apr 15 21:33:35 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jobs.money
     *
     * @mbg.generated Wed Apr 15 21:33:35 CST 2020
     */
    private String money;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jobs.time
     *
     * @mbg.generated Wed Apr 15 21:33:35 CST 2020
     */
    private String time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jobs.company
     *
     * @mbg.generated Wed Apr 15 21:33:35 CST 2020
     */
    private String company;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jobs.scale
     *
     * @mbg.generated Wed Apr 15 21:33:35 CST 2020
     */
    private String scale;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jobs.url
     *
     * @mbg.generated Wed Apr 15 21:33:35 CST 2020
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jobs.job_name
     *
     * @mbg.generated Wed Apr 15 21:33:35 CST 2020
     */
    private String jobName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jobs.id
     *
     * @return the value of jobs.id
     *
     * @mbg.generated Wed Apr 15 21:33:35 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jobs.id
     *
     * @param id the value for jobs.id
     *
     * @mbg.generated Wed Apr 15 21:33:35 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jobs.money
     *
     * @return the value of jobs.money
     *
     * @mbg.generated Wed Apr 15 21:33:35 CST 2020
     */
    public String getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jobs.money
     *
     * @param money the value for jobs.money
     *
     * @mbg.generated Wed Apr 15 21:33:35 CST 2020
     */
    public void setMoney(String money) {
        this.money = money == null ? null : money.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jobs.time
     *
     * @return the value of jobs.time
     *
     * @mbg.generated Wed Apr 15 21:33:35 CST 2020
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jobs.time
     *
     * @param time the value for jobs.time
     *
     * @mbg.generated Wed Apr 15 21:33:35 CST 2020
     */
    public void setTime(String time) {
        this.time = time == null ? null : time.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jobs.company
     *
     * @return the value of jobs.company
     *
     * @mbg.generated Wed Apr 15 21:33:35 CST 2020
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jobs.company
     *
     * @param company the value for jobs.company
     *
     * @mbg.generated Wed Apr 15 21:33:35 CST 2020
     */
    public void setCompany(String company) {
        this.company = company == null ? null : company.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jobs.scale
     *
     * @return the value of jobs.scale
     *
     * @mbg.generated Wed Apr 15 21:33:35 CST 2020
     */
    public String getScale() {
        return scale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jobs.scale
     *
     * @param scale the value for jobs.scale
     *
     * @mbg.generated Wed Apr 15 21:33:35 CST 2020
     */
    public void setScale(String scale) {
        this.scale = scale == null ? null : scale.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jobs.url
     *
     * @return the value of jobs.url
     *
     * @mbg.generated Wed Apr 15 21:33:35 CST 2020
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jobs.url
     *
     * @param url the value for jobs.url
     *
     * @mbg.generated Wed Apr 15 21:33:35 CST 2020
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jobs.job_name
     *
     * @return the value of jobs.job_name
     *
     * @mbg.generated Wed Apr 15 21:33:35 CST 2020
     */
    public String getJobName() {
        return jobName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jobs.job_name
     *
     * @param jobName the value for jobs.job_name
     *
     * @mbg.generated Wed Apr 15 21:33:35 CST 2020
     */
    public void setJobName(String jobName) {
        this.jobName = jobName == null ? null : jobName.trim();
    }
}