package life.mashangkaishi.manongcommunity.model;

public class systemMessage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_message.id
     *
     * @mbg.generated Thu Mar 19 20:24:10 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_message.massage
     *
     * @mbg.generated Thu Mar 19 20:24:10 CST 2020
     */
    private String massage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_message.creat_time
     *
     * @mbg.generated Thu Mar 19 20:24:10 CST 2020
     */
    private String creatTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_message.state
     *
     * @mbg.generated Thu Mar 19 20:24:10 CST 2020
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_message.person
     *
     * @mbg.generated Thu Mar 19 20:24:10 CST 2020
     */
    private String person;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_message.id
     *
     * @return the value of system_message.id
     *
     * @mbg.generated Thu Mar 19 20:24:10 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_message.id
     *
     * @param id the value for system_message.id
     *
     * @mbg.generated Thu Mar 19 20:24:10 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_message.massage
     *
     * @return the value of system_message.massage
     *
     * @mbg.generated Thu Mar 19 20:24:10 CST 2020
     */
    public String getMassage() {
        return massage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_message.massage
     *
     * @param massage the value for system_message.massage
     *
     * @mbg.generated Thu Mar 19 20:24:10 CST 2020
     */
    public void setMassage(String massage) {
        this.massage = massage == null ? null : massage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_message.creat_time
     *
     * @return the value of system_message.creat_time
     *
     * @mbg.generated Thu Mar 19 20:24:10 CST 2020
     */
    public String getCreatTime() {
        return creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_message.creat_time
     *
     * @param creatTime the value for system_message.creat_time
     *
     * @mbg.generated Thu Mar 19 20:24:10 CST 2020
     */
    public void setCreatTime(String creatTime) {
        this.creatTime = creatTime == null ? null : creatTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_message.state
     *
     * @return the value of system_message.state
     *
     * @mbg.generated Thu Mar 19 20:24:10 CST 2020
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_message.state
     *
     * @param state the value for system_message.state
     *
     * @mbg.generated Thu Mar 19 20:24:10 CST 2020
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_message.person
     *
     * @return the value of system_message.person
     *
     * @mbg.generated Thu Mar 19 20:24:10 CST 2020
     */
    public String getPerson() {
        return person;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_message.person
     *
     * @param person the value for system_message.person
     *
     * @mbg.generated Thu Mar 19 20:24:10 CST 2020
     */
    public void setPerson(String person) {
        this.person = person == null ? null : person.trim();
    }
}