package life.mashangkaishi.manongcommunity.model;

import java.util.Date;

public class Task {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.id
     *
     * @mbg.generated Fri Jan 24 17:09:45 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.class_message
     *
     * @mbg.generated Fri Jan 24 17:09:45 CST 2020
     */
    private String classMessage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.gmt_creat
     *
     * @mbg.generated Fri Jan 24 17:09:45 CST 2020
     */
    private String gmtCreat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.deadline
     *
     * @mbg.generated Fri Jan 24 17:09:45 CST 2020
     */
    private Date deadline;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.supplement
     *
     * @mbg.generated Fri Jan 24 17:09:45 CST 2020
     */
    private String supplement;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.description
     *
     * @mbg.generated Fri Jan 24 17:09:45 CST 2020
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.id
     *
     * @return the value of task.id
     *
     * @mbg.generated Fri Jan 24 17:09:45 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.id
     *
     * @param id the value for task.id
     *
     * @mbg.generated Fri Jan 24 17:09:45 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.class_message
     *
     * @return the value of task.class_message
     *
     * @mbg.generated Fri Jan 24 17:09:45 CST 2020
     */
    public String getClassMessage() {
        return classMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.class_message
     *
     * @param classMessage the value for task.class_message
     *
     * @mbg.generated Fri Jan 24 17:09:45 CST 2020
     */
    public void setClassMessage(String classMessage) {
        this.classMessage = classMessage == null ? null : classMessage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.gmt_creat
     *
     * @return the value of task.gmt_creat
     *
     * @mbg.generated Fri Jan 24 17:09:45 CST 2020
     */
    public String getGmtCreat() {
        return gmtCreat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.gmt_creat
     *
     * @param gmtCreat the value for task.gmt_creat
     *
     * @mbg.generated Fri Jan 24 17:09:45 CST 2020
     */
    public void setGmtCreat(String gmtCreat) {
        this.gmtCreat = gmtCreat == null ? null : gmtCreat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.deadline
     *
     * @return the value of task.deadline
     *
     * @mbg.generated Fri Jan 24 17:09:45 CST 2020
     */
    public Date getDeadline() {
        return deadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.deadline
     *
     * @param deadline the value for task.deadline
     *
     * @mbg.generated Fri Jan 24 17:09:45 CST 2020
     */
    public void setDeadline(Date deadline) {
        this.deadline = deadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.supplement
     *
     * @return the value of task.supplement
     *
     * @mbg.generated Fri Jan 24 17:09:45 CST 2020
     */
    public String getSupplement() {
        return supplement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.supplement
     *
     * @param supplement the value for task.supplement
     *
     * @mbg.generated Fri Jan 24 17:09:45 CST 2020
     */
    public void setSupplement(String supplement) {
        this.supplement = supplement == null ? null : supplement.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.description
     *
     * @return the value of task.description
     *
     * @mbg.generated Fri Jan 24 17:09:45 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.description
     *
     * @param description the value for task.description
     *
     * @mbg.generated Fri Jan 24 17:09:45 CST 2020
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}