package life.mashangkaishi.manongcommunity.mapper;

import java.util.List;
import life.mashangkaishi.manongcommunity.model.Jobs;
import life.mashangkaishi.manongcommunity.model.JobsExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Component;

@Component
public interface JobsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jobs
     *
     * @mbg.generated Wed Apr 15 21:33:35 CST 2020
     */
    long countByExample(JobsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jobs
     *
     * @mbg.generated Wed Apr 15 21:33:35 CST 2020
     */
    int deleteByExample(JobsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jobs
     *
     * @mbg.generated Wed Apr 15 21:33:35 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jobs
     *
     * @mbg.generated Wed Apr 15 21:33:35 CST 2020
     */
    int insert(Jobs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jobs
     *
     * @mbg.generated Wed Apr 15 21:33:35 CST 2020
     */
    int insertSelective(Jobs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jobs
     *
     * @mbg.generated Wed Apr 15 21:33:35 CST 2020
     */
    List<Jobs> selectByExampleWithRowbounds(JobsExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jobs
     *
     * @mbg.generated Wed Apr 15 21:33:35 CST 2020
     */
    List<Jobs> selectByExample(JobsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jobs
     *
     * @mbg.generated Wed Apr 15 21:33:35 CST 2020
     */
    Jobs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jobs
     *
     * @mbg.generated Wed Apr 15 21:33:35 CST 2020
     */
    int updateByExampleSelective(@Param("record") Jobs record, @Param("example") JobsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jobs
     *
     * @mbg.generated Wed Apr 15 21:33:35 CST 2020
     */
    int updateByExample(@Param("record") Jobs record, @Param("example") JobsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jobs
     *
     * @mbg.generated Wed Apr 15 21:33:35 CST 2020
     */
    int updateByPrimaryKeySelective(Jobs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jobs
     *
     * @mbg.generated Wed Apr 15 21:33:35 CST 2020
     */
    int updateByPrimaryKey(Jobs record);
}