package life.mashangkaishi.manongcommunity.mapper;

import java.util.List;
import life.mashangkaishi.manongcommunity.model.mailIdentify;
import life.mashangkaishi.manongcommunity.model.mailIdentifyExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface mailIdentifyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mail_identify
     *
     * @mbg.generated Thu Feb 27 21:05:30 CST 2020
     */
    long countByExample(mailIdentifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mail_identify
     *
     * @mbg.generated Thu Feb 27 21:05:30 CST 2020
     */
    int deleteByExample(mailIdentifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mail_identify
     *
     * @mbg.generated Thu Feb 27 21:05:30 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mail_identify
     *
     * @mbg.generated Thu Feb 27 21:05:30 CST 2020
     */
    int insert(mailIdentify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mail_identify
     *
     * @mbg.generated Thu Feb 27 21:05:30 CST 2020
     */
    int insertSelective(mailIdentify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mail_identify
     *
     * @mbg.generated Thu Feb 27 21:05:30 CST 2020
     */
    List<mailIdentify> selectByExampleWithRowbounds(mailIdentifyExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mail_identify
     *
     * @mbg.generated Thu Feb 27 21:05:30 CST 2020
     */
    List<mailIdentify> selectByExample(mailIdentifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mail_identify
     *
     * @mbg.generated Thu Feb 27 21:05:30 CST 2020
     */
    mailIdentify selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mail_identify
     *
     * @mbg.generated Thu Feb 27 21:05:30 CST 2020
     */
    int updateByExampleSelective(@Param("record") mailIdentify record, @Param("example") mailIdentifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mail_identify
     *
     * @mbg.generated Thu Feb 27 21:05:30 CST 2020
     */
    int updateByExample(@Param("record") mailIdentify record, @Param("example") mailIdentifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mail_identify
     *
     * @mbg.generated Thu Feb 27 21:05:30 CST 2020
     */
    int updateByPrimaryKeySelective(mailIdentify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mail_identify
     *
     * @mbg.generated Thu Feb 27 21:05:30 CST 2020
     */
    int updateByPrimaryKey(mailIdentify record);
}