package life.mashangkaishi.manongcommunity.mapper;

import java.util.List;
import life.mashangkaishi.manongcommunity.model.systemMessage;
import life.mashangkaishi.manongcommunity.model.systemMessageExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface systemMessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_message
     *
     * @mbg.generated Thu Mar 19 20:24:10 CST 2020
     */
    long countByExample(systemMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_message
     *
     * @mbg.generated Thu Mar 19 20:24:10 CST 2020
     */
    int deleteByExample(systemMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_message
     *
     * @mbg.generated Thu Mar 19 20:24:10 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_message
     *
     * @mbg.generated Thu Mar 19 20:24:10 CST 2020
     */
    int insert(systemMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_message
     *
     * @mbg.generated Thu Mar 19 20:24:10 CST 2020
     */
    int insertSelective(systemMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_message
     *
     * @mbg.generated Thu Mar 19 20:24:10 CST 2020
     */
    List<systemMessage> selectByExampleWithRowbounds(systemMessageExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_message
     *
     * @mbg.generated Thu Mar 19 20:24:10 CST 2020
     */
    List<systemMessage> selectByExample(systemMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_message
     *
     * @mbg.generated Thu Mar 19 20:24:10 CST 2020
     */
    systemMessage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_message
     *
     * @mbg.generated Thu Mar 19 20:24:10 CST 2020
     */
    int updateByExampleSelective(@Param("record") systemMessage record, @Param("example") systemMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_message
     *
     * @mbg.generated Thu Mar 19 20:24:10 CST 2020
     */
    int updateByExample(@Param("record") systemMessage record, @Param("example") systemMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_message
     *
     * @mbg.generated Thu Mar 19 20:24:10 CST 2020
     */
    int updateByPrimaryKeySelective(systemMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_message
     *
     * @mbg.generated Thu Mar 19 20:24:10 CST 2020
     */
    int updateByPrimaryKey(systemMessage record);
}